# Generated by Django 4.0.3 on 2022-05-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_published',
            new_name='published',
        ),
    ]
