# Generated by Django 4.0.3 on 2022-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_date_published_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
